# PostgreSQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chris-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: lvms-vg1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chris-guestbook
      component: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: quay.io/fedora/postgresql-16:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: chris-db-password
                  key: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chris-db-password
                  key: password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name:  chris-db-config
                  key: db-name
          volumeMounts:
            - name: chris-postgres-data
              mountPath: /var/lib/postgresql
      volumes:
        - name: chris-postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: chris-postgres
spec:
  type: ClusterIP
  selector:
    app: chris-guestbook
    component: postgres
  ports:
    - port: 5432
---
# Redis
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chris-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: lvms-vg1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chris-guestbook
      component: redis
  template:
    metadata:
      labels:
        app: chris-guestbook
        component: redis
    spec:
      containers:
        - name: redis
          image: quay.io/kurs/redis:latest
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chris-redis-password
                  key: password
          volumeMounts:
            - name: chris-redis-data
              mountPath: /var/lib/redis/data
      volumes:
        - name: chris-redis-data
          persistentVolumeClaim:
            claimName: chris-redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: chris-redis
spec:
  type: ClusterIP
  selector:
    app: chris-guestbook
    component: redis
  ports:
    - port: 6379

# Golang Backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chris-guestbook
      component: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: quay.io/hardo314/golang-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db-host
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: redis-port
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8080
