# PostgreSQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chris-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: lvms-vg1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chris-postgres
  template:
    metadata:
      labels:
        app: chris-postgres
    spec:
      containers:
        - name: chris-postgres
          image: quay.io/fedora/postgresql-16:latest
          ports:
            - containerPort: 5432
              resources:
              requests:
                cpu: "10m"
                memory: "64Mi"
              limits:
                cpu: "30m"
                memory: "100Mi"
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: chris-db-password
                  key: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chris-db-password
                  key: password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name:  chris-db-config
                  key: db-name
          volumeMounts:
            - name: chris-postgres-data
              mountPath: /var/lib/postgresql
      volumes:
        - name: chris-postgres-data
          persistentVolumeClaim:
            claimName: chris-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: chris-postgres
spec:
  type: ClusterIP
  selector:
    app: chris-postgres
  ports:
    - port: 5432
---
# Redis
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chris-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: lvms-vg1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chris-redis
  template:
    metadata:
      labels:
        app: chris-redis
    spec:
      containers:
        - name: redis
          image: quay.io/kurs/redis:latest
          ports:
            - containerPort: 6379
              resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"
                limits:
                  cpu: "200m"
                  memory: "256Mi"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chris-redis-password
                  key: password
          volumeMounts:
            - name: chris-redis-data
              mountPath: /var/lib/redis/data
      volumes:
        - name: chris-redis-data
          persistentVolumeClaim:
            claimName: chris-redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: chris-redis
spec:
  type: ClusterIP
  selector:
    app: chris-redis
  ports:
    - port: 6379

# Golang Backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chris-backend
  template:
    metadata:
      labels:
        app: chris-backend
    spec:
      containers:
        - name: chris-backend
          image: ghcr.io/csingfe/guestbook-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "10m"
              memory: "20Mi"
            limits:
              cpu: "30m"
              memory: "40Mi"
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: chris-db-config
                  key: db-host
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: chris-db-config
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: chris-db-config
                  key: redis-port
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chris-redis-password
                  key: password
---,
apiVersion: v1
kind: Service
metadata:
  name: chris-backend
spec:
  type: ClusterIP
  selector:
    app: chrisbackend
  ports:
    - port: 8080
