apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chris-frontend
  template:
    metadata:
      labels:
        app: chris-frontend
    spec:
      containers:
        - name: chris-frontend
          image: ghcr.io/csingfe/guestbook-frontend:latest   #
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "10m"
              memory: "50Mi"
            requests:
              cpu: "30m"
              memory: "80Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: chris-frontend
  ports:
    - port: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: chris-frontend
spec:
  to:
    kind: Service
    name: chris-frontend