apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris-frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: chris-frontend
  template:
    metadata:
      labels:
        app: chris-frontend
      annotations:
        restartedAt: "2026-01-07-11-37"
    spec:
      containers:
        - name: chris-frontend
          image: ghcr.io/csingfe/chris-guest-argo/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "100m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: chris-frontend
spec:
  type: ClusterIP
  selector:
    app: chris-frontend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: chris-frontend
spec:
  to:
    kind: Service
    name: chris-frontend
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
